import * as RNLocalize from "react-native-localize";

export const allPhoneLocales = RNLocalize.getLocales();

export const mainAppTranslations = {
	en: {
		air: "Air",
		airplane: "Airplane",
		airport: "Airport",
		axe: "Axe",
		bambooForest: "Bamboo Forest",
		bambooFountain: "Bamboo Fountain",
		bank: "Bank",
		bar: "Bar",
		basketball: "Basketball",
		beach: "Beach",
		billiards: "Billiards",
		birds: "Birds",
		boat: "Boat",
		boiling: "Boiling",
		book: "Book",
		bridgesAndKisses: "Bridges & Kisses",
		cafeteria: "Cafeteria",
		campfire: "Campfire",
		candle: "Candle",
		cards: "Cards",
		catPurr: "Cat Purr",
		cave: "Cave",
		chinatown: "Chinatown",
		city: "City",
		clock: "Clock",
		cobblestoneStreet: "Cobbl. Street",
		coffeeBeans: "Coffee Beans",
		coins: "Coins",
		conditioner: "Conditioner",
		constructionSite: "Construction Site",
		countryside: "Countryside",
		cuckoo: "Cuckoo",
		destiny: "Destiny",
		dirtWalking: "Dirt Walking",
		dishwasher: "Dishwasher",
		driving: "Driving",
		droplets: "Droplets",
		fan: "Fan",
		fieldWay: "Field Way",
		fireworks: "Fireworks",
		forest: "Forest",
		fountain: "Fountain",
		glass: "Glass",
		heartbeat: "Heartbeat",
		horse: "Horse",
		iceHockey: "Ice Hockey",
		ice: "Ice",
		interstellar: "Interstellar",
		jungle: "Jungle",
		keyboard: "Keyboard",
		kitchen: "Kitchen",
		lake: "Lake",
		leaves: "Leaves",
		longJourney: "Long Journey",
		magazine: "Magazine",
		marketplace: "Marketplace",
		mars: "Mars",
		money: "Money",
		moon: "Moon",
		morning: "Morning",
		mountainRoad: "Mountain Road",
		museum: "Museum",
		musicBox: "Music Box",
		nightPark: "Night Park",
		nightSea: "Night Sea",
		ocean: "Ocean",
		office: "Office",
		onionCutting: "Onion Cutting",
		painting: "Painting",
		pencil: "Pencil",
		penguin: "Penguin",
		piano: "Piano",
		pingPong: "Ping-pong",
		port: "Port",
		pouringWater: "Pouring Water",
		prismLight: "Prism Light",
		rain: "Rain",
		restaurant: "Restaurant",
		river: "River",
		rollerCoaster: "Roller Coaster",
		roof: "Roof",
		sandStorm: "Sand Storm",
		shovel: "Shovel",
		silence: "Silence",
		sky: "Sky",
		snow: "Snow",
		storm: "Storm",
		submarine: "Submarine",
		summerDream: "Summer Dream",
		summerInParis: "Summer in Paris",
		supermarket: "Supermarket",
		swamp: "Swamp",
		television: "Television",
		temple: "Temple",
		tennis: "Tennis",
		toyBlocks: "Toy Blocks",
		train: "Train",
		trolley: "Trolley",
		typewriter: "Typewriter",
		umbrella: "Umbrella",
		underwater: "Underwater",
		voicesOfNature: "Voices of Nature",
		volcano: "Volcano",
		washer: "Washer",
		waterfall: "Waterfall",
		wind: "Wind",
		windAndSilence: "Wind and Silence",
		windChime: "Wind Chime",
		window: "Window",
		yacht: "Yacht",

		goodNight: "Good night",
		goodMorning: "Good morning",
		goodAfternoon: "Good afternoon",
		goodEvening: "Good evening",

		youGotCoins1: "Congrats!",
		youGotCoins2: "You have earned",
		youGotCoins3: "coins",

		focusEndedAhead: "Focus ended ahead of time",
		meditationEndedAhead: "Meditation ended ahead of time",
		napEndedAhead: "Nap ended ahead of time",
		timeWillNotBeRecorded: "The time will not be recorded in statistics",

		oops: "Oops!",
		proVersionIsAlreadyActive: "Pro version is already active",
		youHaveAlreadyPurchasedTheProVersion: "You have already purchased the pro version",
		youHaventPurchasedProVersion: "You have not purchased the pro version yet",
		somethingWentWrong: "Something went wrong",
		notEnoughFunds: "Insufficient funds!",
		operationSuccess: "Operation was successfully completed!",
		error: "Error",
		cancel: "Cancel",
		warning: "Warning",
		skipAuthWarn1: "Are you sure you want to skip authorization?",
		skipAuthWarn2: "Your personal data will be lost if you uninstall the application",
		alreadyDownloadedWarn: "Sound has already been loaded",
		missingPhoneNumberErr: "Phone number is missing",
		invalidPhoneNumberErr1: "Please, use the following format:",
		invalidPhoneNumberErr2: "+(country code)(phone number)",
		quotaExceededErr: "SMS quota has been exceeded",
		userDisabledErr: "User has been disabled",
		noInternetConnectionErr: "No internet connection!",
		immersiveModeAlert1: "When you exit the application, after",
		immersiveModeAlert2: "seconds, the timer will be automatically turned off",

		authIntroduction1: "Rise is your productivity control assistant...",
		authIntroduction2: "...to help you focus and relax.",
		authIntroduction3: "Use your time wisely with Rise.",
		pleaseAuthencticate: "Please log in",
		usingSocialMedia: "Using social media",
		enterYourPhoneNumber: "Enter your phone number",
		enterConfirmationCode: "Enter confirmation code",
		completeRegistration: "Complete registration",
		firstName: "First name",
		lastName: "Last name",
		dateOfBirth: "Date of Birth",
		welcome: "Welcome!",
		or: "or",
		continue: "Continue",
		registration: "Registration",
		skipAuthorization: "Skip authorization",
		aboutMeText: "Hello! I am a developer from Moldova. I have been programming long enough to be able to develop this application. As a student, I am very concerned about productivity, which is why I present to you Rise. You can escape from the daily hustle and bustle by meditating to relaxing sounds; take a nap without fear of oversleeping everything in the world, and, of course, completely focus on what you love. Welcome!",

		deleteAccountWarning: "Are you sure you want to delete the account?",
		logOutWarning: "Are you sure you want to log out?",
		soundShop: "Sound shop",
		noSounds: "Oops, nothing here!",
		happyBirthday: "Happy Birthday,",
		yes: "Yes",
		no: "No",

		secs: "s",
		perMin: "per min",
		min: "min",
		hour: "hr",
		time: "time",
		times: "times",
		meditation: "Meditation",
		focus: "Focus",
		nap: "Nap",
		currentBalance: "Current balance:",
		howToGetCoins1: "How to get coins?",
		howToGetCoins2: "You get 100 coins for 1 hour of using any mode",

		shopMainCategory: "General",
		shopDownloadButton: "Upload",
		shopDownloadedButton: "Uploaded",

		timer: "Timer",
		pomodoro: "Pomodoro",
		infinite: "Infinite",

		focusModesChoose: "Modes",
		meditationBreath: "Breath",
		napAlarm: "Alarm",
		
		modeSoundsChoose: "Sounds",

		modeTimeToFocus: "Time to focus",
		modeTimeToMeditate: "Time to meditate",
		modeTimeToNap: "Time to nap",

		modeChooseNecessaryTime: "Choose necessary time",
		modePlayButton: "Start",
		modePauseButton: "Pause",
		modeStopButton: "Stop",
		modeResumeButton: "Resume",
		inhale: "Inhale",
		exhale: "Exhale",

		vibration: "Vibration",
		breathSounds: "Breath sounds",
		balancedBreath: "Balanced breath",
		ringtone: "Ringtone",
		alarmDuration: "Alarm duration",
		sound: "Sound",
		advanced: "Advanced",
		focusTime: "Focus time",
		breakTime: "Break time",
		longBreakTime: "Long break time",
		longBreakEvery: "Long break every",
		autoSwitch: "Auto switch",
		fullImmersion: "Full immersion",
		screenOn: "Disable sleep mode",
		save: "Save",

		settings: "Settings",
		settingsAccount: "Account",
		settingsLanguage: "Language",
		settingsRateUs: "Rate us",
		settingsAboutMe: "About me",

		paidExtendedVersion: "Paid extended version",
		freeLimitedVersion: "Free limited version",
		updateVersion: "Upgrade",
		restoreVersion: "Restore",
		quitFromAccount: "Log out",
		deleteAccount: "Delete account",
	},
	ru: {
		air: "Воздух",
		airplane: "Самолет",
		airport: "Аэропорт",
		axe: "Топор",
		bambooForest: "Бамбук",
		bambooFountain: "Ручей",
		bank: "Банк",
		bar: "Бар",
		basketball: "Баскетбол",
		beach: "Пляж",
		billiards: "Бильярд",
		birds: "Птицы",
		boat: "Лодка",
		boiling: "Кипячение",
		book: "Книга",
		bridgesAndKisses: "Мосты и поцелуи",
		cafeteria: "Кафетерий",
		campfire: "Костер",
		candle: "Свеча",
		cards: "Карты",
		catPurr: "Мурлыканье",
		cave: "Пещера",
		chinatown: "Чайна-таун",
		city: "Город",
		clock: "Часы",
		cobblestoneStreet: "Мощеная улица",
		coffeeBeans: "Кофе",
		coins: "Монеты",
		conditioner: "Кондиционер",
		constructionSite: "Стр. площадка",
		countryside: "Деревня",
		cuckoo: "Кукушка",
		destiny: "Судьба",
		dirtWalking: "Грязь",
		dishwasher: "Посудомойка",
		driving: "Вождение",
		droplets: "Капли",
		fan: "Вентилятор",
		fieldWay: "Поле",
		fireworks: "Фейерверк",
		forest: "Лес",
		fountain: "Фонтан",
		glass: "Стекло",
		heartbeat: "Сердцебиение",
		horse: "Лошадь",
		iceHockey: "Хоккей на льду",
		ice: "Лед",
		interstellar: "Межзвездный",
		jungle: "Джунгли",
		keyboard: "Клавиатура",
		kitchen: "Кухня",
		lake: "Озеро",
		leaves: "Листья",
		longJourney: "Долгий путь",
		magazine: "Газета",
		marketplace: "Рынок",
		mars: "Марс",
		money: "Деньги",
		moon: "Луна",
		morning: "Утро",
		mountainRoad: "Дорога в горах",
		museum: "Музей",
		musicBox: "Муз. шкатулка",
		nightPark: "Ночной парк",
		nightSea: "Ночное море",
		ocean: "Океан",
		office: "Офис",
		onionCutting: "Нарезание лука",
		painting: "Рисование",
		pencil: "Карандаш",
		penguin: "Пингвин",
		piano: "Пианино",
		pingPong: "Пинг-понг",
		port: "Порт",
		pouringWater: "Лить воду",
		prismLight: "Призмат. свет",
		rain: "Дождь",
		restaurant: "Ресторан",
		river: "Река",
		rollerCoaster: "Аттракцион",
		roof: "Крыша",
		sandStorm: "Песчаная буря",
		shovel: "Лопата",
		silence: "Тишина",
		sky: "Небо",
		snow: "Снег",
		storm: "Шторм",
		submarine: "Подв. лодка",
		summerDream: "Летний сон",
		summerInParis: "Лето в Париже",
		supermarket: "Супермаркет",
		swamp: "Болото",
		television: "Телевидение",
		temple: "Храм",
		tennis: "Теннис",
		toyBlocks: "Конструктор",
		train: "Поезд",
		trolley: "Трамвай",
		typewriter: "Печ. машинка",
		umbrella: "Зонтик",
		underwater: "Под водой",
		voicesOfNature: "Голоса природы",
		volcano: "Вулкан",
		washer: "Стир. машина",
		waterfall: "Водопад",
		wind: "Ветер",
		windAndSilence: "Ветер и тишина",
		windChime: "Колокольчик",
		window: "Окно",
		yacht: "Яхта",

		goodNight: "Доброй ночи",
		goodMorning: "Доброе утро",
		goodAfternoon: "Добрый день",
		goodEvening: "Добрый вечер",

		focusEndedAhead: "Фокус закончился раньше времени",
		meditationEndedAhead: "Медитация закончилась раньше времени",
		napEndedAhead: "Дрём закончился раньше времени",
		timeWillNotBeRecorded: "Время не будет записано в статистику",

		oops: "Упс!",
		proVersionIsAlreadyActive: "Про версия уже активна",
		youHaveAlreadyPurchasedTheProVersion: "Вы уже приобрели про версию",
		youHaventPurchasedProVersion: "Вы не приобрели про версию",
		somethingWentWrong: "Что-то пошло не так",
		notEnoughFunds: "Недостаточно средств!",
		operationSuccess: "Операция прошла успешно!",
		error: "Ошибка",
		cancel: "Отмена",
		warning: "Предупреждение",
		skipAuthWarn1: "Вы уверены, что хотите пропустить авторизацию?",
		skipAuthWarn2: "Ваши личные данные пропадут в случае удаления приложения",
		alreadyDownloadedWarn: "Звук уже загружен",
		missingPhoneNumberErr: "Номер телефона отсутствует",
		invalidPhoneNumberErr1: "Пожалуйста, используйте следующий формат:",
		invalidPhoneNumberErr2: "+(код страны)(номер телефона)",
		quotaExceededErr: "Превышена квота SMS",
		userDisabledErr: "Пользователь был отключен",
		noInternetConnectionErr: "Нет соединения с интернетом!",
		immersiveModeAlert1: "При выходе из приложения, по прошествии",
		immersiveModeAlert2: "секунд, таймер будет автоматически выключен",

		authIntroduction1: "Rise - ваш помощник по контролю продуктивности...",
		authIntroduction2: "...поможет вам сфокусироваться и расслабиться.",
		authIntroduction3: "Используйте время с умом вместе с Rise.",
		pleaseAuthencticate: "Пожалуйста авторизуйтесь",
		usingSocialMedia: "С помощью соц. сетей",
		enterYourPhoneNumber: "Введите свой номер телефона",
		enterConfirmationCode: "Введите код подтверждения",
		completeRegistration: "Завершить регистрацию",
		firstName: "Имя",
		lastName: "Фамилия",
		dateOfBirth: "Дата рождения",
		welcome: "Добро пожаловать!",
		or: "или",
		continue: "Продолжить",
		registration: "Регистрация",
		skipAuthorization: "Пропустить авторизацию",
		aboutMeText: "Здравствуйте! Я разработчик из Молдовы. Я программирую достаточно долго, чтобы суметь разработать это приложение. Будучи студентом, я сильно обеспокоен вопросом продуктивности, поэтому я представляю вам Rise. Вы можете отвлечься от повседневной суеты, медитируя под расслабляющие звуки; подремать, не боясь проспать все на свете и, конечно же, полностью сфокусироваться на любимом деле. Добро пожаловать!",

		deleteAccountWarning: "Вы уверены, что хотите удалить аккаунт?",
		logOutWarning: "Вы уверены, что хотите выйти из аккаунта?",
		soundShop: "Магазин звуков",
		noSounds: "Упс, здесь ничего нет!",
		happyBirthday: "С Днём Рождения,",
		yes: "Да",
		no: "Нет",

		youGotCoins1: "Поздравляю!",
		youGotCoins2: "Вы заработали",
		youGotCoins3: "монет",

		secs: "сек",
		perMin: "в мин",
		min: "мин",
		hour: "ч",
		time: "раз",
		times: "раза",
		meditation: "Медитация",
		focus: "Фокус",
		nap: "Дрём",
		currentBalance: "Текущий баланс:",
		howToGetCoins1: "Как получить монеты?",
		howToGetCoins2: "Вы получаете 100 монет за 1 час использования любого режима",

		shopMainCategory: "Общее",
		shopDownloadButton: "Скачать",
		shopDownloadedButton: "Скачано",

		timer: "Таймер",
		pomodoro: "Помодоро",
		infinite: "Бесконечный",

		focusModesChoose: "Режимы",
		meditationBreath: "Дыхание",
		napAlarm: "Будильник",

		modeSoundsChoose: "Звуки",

		modeTimeToFocus: "Время сосредоточиться",
		modeTimeToMeditate: "Время медитировать",
		modeTimeToNap: "Время вздремнуть",

		modeChooseNecessaryTime: "Выберите необходимое время",
		modePlayButton: "Старт",
		modePauseButton: "Пауза",
		modeStopButton: "Стоп",
		modeResumeButton: "Старт",
		inhale: "Вдох",
		exhale: "Выдох",

		vibration: "Вибрация",
		breathSounds: "Звуки дыхания",
		balancedBreath: "Дыхание",
		ringtone: "Рингтон",
		alarmDuration: "Длительность будильника",
		sound: "Звук",
		advanced: "Расширенные",
		focusTime: "Время фокуса",
		breakTime: "Время отдыха",
		longBreakTime: "Время долгого отдыха",
		longBreakEvery: "Долгий отдых каждый",
		autoSwitch: "Автопереключение",
		fullImmersion: "Полное погружение",
		screenOn: "Отключить спящий режим",
		save: "Сохранить",

		settings: "Настройки",
		settingsAccount: "Аккаунт",
		settingsLanguage: "Язык",
		settingsRateUs: "Оценить нас",
		settingsAboutMe: "Обо мне",
		
		paidExtendedVersion: "Платная расширенная версия",
		freeLimitedVersion: "Бесплатная ограниченная версия",
		updateVersion: "Улучшить",
		restoreVersion: "Восстановить",
		quitFromAccount: "Выйти из аккаунта",
		deleteAccount: "Удалить аккаунт",
	},
	es: {
		air: "Aire",
		airplane: "Avión",
		airport: "Aeropuerto",
		axe: "Hacha",
		bambooForest: "Bosque de bambú",
		bambooFountain: "Fuente de bambú",
		bank: "Banco",
		bar: "Bar",
		basketball: "Baloncesto",
		beach: "Playa",
		billiards: "Billar",
		birds: "Aves",
		boat: "Barco",
		boiling: "Hirviendo",
		book: "Libro",
		bridgesAndKisses: "Puentes y besos",
		cafeteria: "Cafetería",
		campfire: "Hoguera",
		candle: "Vela",
		cards: "Tarjetas",
		catPurr: "Ronroneo",
		cave: "Cueva",
		chinatown: "Chinatown",
		city: "Ciudad",
		clock: "Reloj",
		cobblestoneStreet: "Calle adoquinada",
		coffeeBeans: "Granos de café",
		coins: "Monedas",
		conditioner: "Acondicionador",
		constructionSite: "Sitio de constr.",
		countryside: "Campo",
		cuckoo: "Cuco",
		destiny: "Destino",
		dirtWalking: "Caminando",
		dishwasher: "Lavavajillas",
		driving: "Conduciendo",
		droplets: "Gotas",
		fan: "Ventilador",
		fieldWay: "Campo",
		fireworks: "Fuegos artificiales",
		forest: "Bosque",
		fountain: "Fuente",
		glass: "Vidrio",
		heartbeat: "Latido del corazón",
		horse: "Caballo",
		iceHockey: "Hockey sobre hielo",
		ice: "Hielo",
		interstellar: "Interestelar",
		jungle: "Selva",
		keyboard: "Teclado",
		kitchen: "Cocina",
		lake: "Lago",
		leaves: "Sale de",
		longJourney: "Viaje largo",
		magazine: "Revista",
		marketplace: "Mercado",
		mars: "Marte",
		money: "Dinero",
		moon: "Luna",
		morning: "Mañana",
		mountainRoad: "Carr. de montaña",
		museum: "Museo",
		musicBox: "Caja de música",
		nightPark: "Parque nocturno",
		nightSea: "Mar de noche",
		ocean: "Oceano",
		office: "Oficina",
		onionCutting: "Corte de cebolla",
		painting: "Cuadro",
		pencil: "Lápiz",
		penguin: "Pingüino",
		piano: "Piano",
		pingPong: "Ping-pong",
		port: "Puerto",
		pouringWater: "Echando agua",
		prismLight: "Prisma de luz",
		rain: "Lluvia",
		restaurant: "Restaurante",
		river: "Río",
		rollerCoaster: "Montaña rusa",
		roof: "Techo",
		sandStorm: "Tormenta de arena",
		shovel: "Pala",
		silence: "Silencio",
		sky: "Cielo",
		snow: "Nieve",
		storm: "Tormenta",
		submarine: "Submarino",
		summerDream: "Sueño de verano",
		summerInParis: "Verano en Paris",
		supermarket: "Supermercado",
		swamp: "Pantano",
		television: "Televisión",
		temple: "Templo",
		tennis: "Tenis",
		toyBlocks: "Bloques de jug.",
		train: "Tren",
		trolley: "Carretilla",
		typewriter: "Tranvía",
		umbrella: "Paraguas",
		underwater: "Bajo el agua",
		voicesOfNature: "Voces de la natur.",
		volcano: "Volcán",
		washer: "Lavadora",
		waterfall: "Cascada",
		wind: "Viento",
		windAndSilence: "Viento y silencio",
		windChime: "Carillón de viento",
		window: "Ventana",
		yacht: "Yate",
		
		goodNight: "Buenas noches",
		goodMorning: "Buenos días",
		goodAfternoon: "Buen día",
		goodEvening: "Buenas noches",

		youGotCoins1: "¡Felicitaciones!",
		youGotCoins2: "Has ganado",
		youGotCoins3: "monedas",

		focusEndedAhead: "El enfoque terminó antes de tiempo",
		meditationEndedAhead: "La meditación terminó antes de tiempo",
		napEndedAhead: "El sueño terminó antes de tiempo",
		timeWillNotBeRecorded: "El tiempo no se registrará en las estadísticas",

		oops: "¡UPS!",
		proVersionIsAlreadyActive: "La versión pro ya está activa",
		youHaveAlreadyPurchasedTheProVersion: "Ya has comprado la versión pro",
		youHaventPurchasedProVersion: "Aún no has comprado la versión pro",
		somethingWentWrong: "Algo salió mal",
		notEnoughFunds: "¡Fondos insuficientes!",
		operationSuccess: "¡La operación se completó con éxito!",
		error: "Error",
		cancel: "Cancelación",
		warning: "Advertencia",
		skipAuthWarn1: "¿Está seguro de que desea omitir la autorización?",
		skipAuthWarn2: "Sus datos personales se perderán si desinstala la aplicación",
		alreadyDownloadedWarn: "El sonido ya se ha cargado",
		missingPhoneNumberErr: "Falta el número de teléfon",
		invalidPhoneNumberErr1: "Por favor, use el siguiente formato:",
		invalidPhoneNumberErr2: "+(código de país)(número de teléfono)",
		quotaExceededErr: "Se superó la cuota de SMS",
		userDisabledErr: "El usuario ha sido deshabilitado",
		noInternetConnectionErr: "¡Sin conexión a Internet!",
		immersiveModeAlert1: "Cuando salga de la aplicación, después de",
		immersiveModeAlert2: "segundos, el temporizador se apagará automáticamente",

		authIntroduction1: "Rise es su asistente de control de productividad...",
		authIntroduction2: "...para ayudarlo a concentrarse y relajarse.",
		authIntroduction3: "Usa su tiempo sabiamente con Rise.",
		pleaseAuthencticate: "Por favor iniciar sesión",
		usingSocialMedia: "Usando las redes sociales",
		enterYourPhoneNumber: "Ingrese su número telefónico",
		enterConfirmationCode: "Introducir el código de confirmación",
		completeRegistration: "Registro completo",
		firstName: "Nombre",
		lastName: "Apellido",
		dateOfBirth: "Fecha de nacimiento",
		welcome: "¡Bienvenidos!",
		or: "o",
		continue: "Continuar",
		registration: "Registro",
		skipAuthorization: "Omitir autorización",
		aboutMeText: "¡Hola! Soy un desarrollador de Moldavia. He estado programando el tiempo suficiente para poder desarrollar esta aplicación. Como estudiante me preocupa mucho la productividad, por eso te presento Rise. Puede dejar de pensar en su ajetreo diario meditando con sonidos relajantes; toma una siesta, no tengas miedo de dormir todo lo que hay en el mundo y, por supuesto, concéntrate por completo en lo que amas. ¡Bienvenido!",
		
		deleteAccountWarning: "¿Estás seguro de que quieres borrar la cuenta?",
		logOutWarning: "¿Estás seguro de que quieres cerrar sesión?",
		soundShop: "Tienda de sonido",
		noSounds: "¡Ups, no hay nada aquí!",
		happyBirthday: "Feliz cumpleaños,",
		yes: "Sí",
		no: "No",

		secs: "s",
		perMin: "por min",
		min: "min",
		hour: "hr",
		time: "vec",
		times: "veces",
		meditation: "Meditación",
		focus: "Enfocar",
		nap: "Sueño",
		currentBalance: "Saldo actual:",
		howToGetCoins1: "¿Cómo conseguir monedas?",
		howToGetCoins2: "Obtienes 100 monedas por 1 hora de usar cualquier modo",

		shopMainCategory: "General",
		shopDownloadButton: "Subir",
		shopDownloadedButton: "Subido",

		timer: "Temporizador",
		pomodoro: "Pomodoro",
		infinite: "Infinito",

		focusModesChoose: "Modos",
		meditationBreath: "Respiración",
		napAlarm: "Alarma",

		modeSoundsChoose: "Sonidos",

		modeTimeToFocus: "Tiempo para concentrarse",
		modeTimeToMeditate: "Tiempo para meditar",
		modeTimeToNap: "Tiempo para el sueño",

		modeChooseNecessaryTime: "Elige el tiempo necesario",
		modePlayButton: "Empezar",
		modePauseButton: "Pausar",
		modeStopButton: "Detener",
		modeResumeButton: "Resumir",
		inhale: "Inhalar",
		exhale: "Exhalar",

		vibration: "Vibración",
		breathSounds: "Sonidos respiratorios",
		balancedBreath: "Respiración equilibrada",
		ringtone: "Tono de llamada",
		alarmDuration: "Duración de la alarma",
		sound: "Sonido",
		advanced: "Avanzados",
		focusTime: "Tiempo de concentración",
		breakTime: "Tiempo de descanso",
		longBreakTime: "Tiempo de descanso extenso",
		longBreakEvery: "Descanso largo cada",
		autoSwitch: "Cambio automático",
		fullImmersion: "Inmersión completa",
		screenOn: "Desactivar el modo de reposo",
		save: "Guardar",

		settings: "Ajustes",
		settingsAccount: "Cuenta",
		settingsLanguage: "Idioma",
		settingsRateUs: "Nos califica",
		settingsAboutMe: "Sobre mí",

		paidExtendedVersion: "Versión extendida de pago",
		freeLimitedVersion: "Versión limitada gratuita",
		updateVersion: "Mejorar",
		restoreVersion: "Restaurar",
		quitFromAccount: "Cerrar sesión",
		deleteAccount: "Borrar cuenta",
	},
};