import I18n from "i18n-js";
import { Source } from "react-native-fast-image";

let counter = 0;

export const SoundNamesTemp: { [key: string]: { index: number, type: string | string[], name: string, price: number } } = {
	"Air": {
		name: I18n.t("air"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Airplane": {
		name: I18n.t("airplane"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Airport": {
		name: I18n.t("airport"),
		index: counter++,
		type: "meditation",
		price: 0,
	},
	"Axe": {
		name: I18n.t("axe"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Bamboo Forest": {
		name: I18n.t("bambooForest"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Bamboo Fountain": {
		name: I18n.t("bambooFountain"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Bank": {
		name: I18n.t("bank"),
		index: counter++,
		type: "meditation",
		price: 0,
	},
	"Bar": {
		name: I18n.t("bar"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Basketball": {
		name: I18n.t("basketball"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Beach": {
		name: I18n.t("beach"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Billiard": {
		name: I18n.t("billiards"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Birds": {
		name: I18n.t("birds"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Boat": {
		name: I18n.t("boat"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Boiling": {
		name: I18n.t("boiling"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Book": {
		name: I18n.t("book"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Bridges and Kisses": {
		name: I18n.t("bridgesAndKisses"),
		index: counter++,
		type: "meditation",
		price: 0,
	},
	"Cafeteria": {
		name: I18n.t("cafeteria"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Campfire": {
		name: I18n.t("campfire"),
		index: counter++,
		type: "nap",
		price: 0,
	},
	"Candle": {
		name: I18n.t("candle"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Cards": {
		name: I18n.t("cards"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Cat Purr": {
		name: I18n.t("catPurr"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Cave": {
		name: I18n.t("cave"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Chinatown": {
		name: I18n.t("chinatown"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"City": {
		name: I18n.t("city"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Clock": {
		name: I18n.t("clock"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Cobblestone Street": {
		name: I18n.t("cobblestoneStreet"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Coffee Beans": {
		name: I18n.t("coffeeBeans"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Coins": {
		name: I18n.t("coins"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Conditioner": {
		name: I18n.t("conditioner"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Construction Site": {
		name: I18n.t("constructionSite"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Countryside": {
		name: I18n.t("countryside"),
		index: counter++,
		type: "meditation",
		price: 0,
	},
	"Cuckoo": {
		name: I18n.t("cuckoo"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Destiny": {
		name: I18n.t("destiny"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Dirt Walking": {
		name: I18n.t("dirtWalking"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Dishwasher": {
		name: I18n.t("dishwasher"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Driving": {
		name: I18n.t("driving"),
		index: counter++,
		type: "nap",
		price: 500,
	},
	"Droplets": {
		name: I18n.t("droplets"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Fan": {
		name: I18n.t("fan"),
		index: counter++,
		type: ["focus", "nap"],
		price: 500,
	},
	"Field Way": {
		name: I18n.t("fieldWay"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Fireworks": {
		name: I18n.t("fireworks"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Forest": {
		name: I18n.t("forest"),
		index: counter++,
		type: ["focus", "meditation", "nap"],
		price: 0,
	},
	"Fountain": {
		name: I18n.t("fountain"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Glass": {
		name: I18n.t("glass"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Heartbeat": {
		name: I18n.t("heartbeat"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Horse": {
		name: I18n.t("horse"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Ice Hockey": {
		name: I18n.t("iceHockey"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Ice": {
		name: I18n.t("ice"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Interstellar": {
		name: I18n.t("interstellar"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Jungle": {
		name: I18n.t("jungle"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Keyboard": {
		name: I18n.t("keyboard"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Kitchen": {
		name: I18n.t("kitchen"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Lake": {
		name: I18n.t("lake"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Leaves": {
		name: I18n.t("leaves"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Long Journey": {
		name: I18n.t("longJourney"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Magazine": {
		name: I18n.t("magazine"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Marketplace": {
		name: I18n.t("marketplace"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Mars": {
		name: I18n.t("mars"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Money": {
		name: I18n.t("money"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Moon": {
		name: I18n.t("moon"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Morning": {
		name: I18n.t("morning"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Mountain Road": {
		name: I18n.t("mountainRoad"),
		index: counter++,
		type: "meditation",
		price: 0,
	},
	"Museum": {
		name: I18n.t("museum"),
		index: counter++,
		type: "meditation",
		price: 0,
	},
	"Music Box": {
		name: I18n.t("musicBox"),
		index: counter++,
		type: "nap",
		price: 500,
	},
	"Night Park": {
		name: I18n.t("nightPark"),
		index: counter++,
		type: "nap",
		price: 0,
	},
	"Night Sea": {
		name: I18n.t("nightSea"),
		index: counter++,
		type: "nap",
		price: 0,
	},
	"Ocean": {
		name: I18n.t("ocean"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Office": {
		name: I18n.t("office"),
		index: counter++,
		type: "meditation",
		price: 0,
	},
	"Onion Cutting": {
		name: I18n.t("onionCutting"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Painting": {
		name: I18n.t("painting"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Pencil": {
		name: I18n.t("pencil"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Penguin": {
		name: I18n.t("penguin"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Piano": {
		name: I18n.t("piano"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Ping-pong": {
		name: I18n.t("pingPong"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Port": {
		name: I18n.t("port"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Pouring Water": {
		name: I18n.t("pouringWater"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Prism Light": {
		name: I18n.t("prismLight"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Rain": {
		name: I18n.t("rain"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Restaurant": {
		name: I18n.t("restaurant"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"River": {
		name: I18n.t("river"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Roller Coaster": {
		name: I18n.t("rollerCoaster"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Roof": {
		name: I18n.t("roof"),
		index: counter++,
		type: "nap",
		price: 0,
	},
	"Sand Storm": {
		name: I18n.t("sandStorm"),
		index: counter++,
		type: "nap",
		price: 500,
	},
	"Shovel": {
		name: I18n.t("shovel"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Silence": {
		name: I18n.t("silence"),
		index: counter++,
		type: "nap",
		price: 500,
	},
	"Sky": {
		name: I18n.t("sky"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Snow": {
		name: I18n.t("snow"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Storm": {
		name: I18n.t("storm"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Submarine": {
		name: I18n.t("submarine"),
		index: counter++,
		type: "nap",
		price: 500,
	},
	"Summer Dream": {
		name: I18n.t("summerDream"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Summer in Paris": {
		name: I18n.t("summerInParis"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Supermarket": {
		name: I18n.t("supermarket"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Swamp": {
		name: I18n.t("swamp"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Television": {
		name: I18n.t("television"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Temple": {
		name: I18n.t("temple"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Tennis": {
		name: I18n.t("tennis"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Toy Blocks": {
		name: I18n.t("toyBlocks"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Train": {
		name: I18n.t("train"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Trolley": {
		name: I18n.t("trolley"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Typewriter": {
		name: I18n.t("typewriter"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Umbrella": {
		name: I18n.t("umbrella"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Underwater": {
		name: I18n.t("underwater"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Voices of Nature": {
		name: I18n.t("voicesOfNature"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 0,
	},
	"Volcano": {
		name: I18n.t("volcano"),
		index: counter++,
		type: "focus",
		price: 0,
	},
	"Washer": {
		name: I18n.t("washer"),
		index: counter++,
		type: "focus",
		price: 500,
	},
	"Waterfall": {
		name: I18n.t("waterfall"),
		index: counter++,
		type: "meditation",
		price: 500,
	},
	"Wind": {
		name: I18n.t("wind"),
		index: counter++,
		type: "nap",
		price: 0,
	},
	"Wind and Silence": {
		name: I18n.t("windAndSilence"),
		index: counter++,
		type: "nap",
		price: 0,
	},
	"Wind Chime": {
		name: I18n.t("windChime"),
		index: counter++,
		type: ["meditation", "nap"],
		price: 500,
	},
	"Window": {
		name: I18n.t("window"),
		index: counter++,
		type: "nap",
		price: 0,
	},
	"Yacht": {
		name: I18n.t("yacht"),
		index: counter++,
		type: "nap",
		price: 500,
	},
};

let SoundNamesTempOrdered: {
    [key: string]: {
        index: number;
        type: string | string[];
		name: string;
    };
} | null = Object.keys(SoundNamesTemp).sort().reduce(
	(obj: { [key: string]: { index: number, type: string | string[], name: string } }, key) => { 
		obj[key] = SoundNamesTemp[key]; 
		return obj;
	}, 
	{}
);

export const SoundNames = Object.keys(SoundNamesTempOrdered);
export const SoundPathNames = Object.values(SoundNamesTemp).map(val => val.name);

SoundNamesTempOrdered = null;
counter = 0;

export const SoundPath: { [x: string]: Source } = {
	[SoundPathNames[counter++]]: require("_assets/images/Air.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Airplane.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Airport.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Axe.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/BambooForest.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/BambooFountain.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Bank.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Bar.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Basketball.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Beach.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Billiard.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Birds.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Boat.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Boiling.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Book.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/BridgesAndKisses.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Cafeteria.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Campfire.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Candle.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Cards.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/CatPurr.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Cave.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Chinatown.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/City.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Clock.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/CobblestoneStreet.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/CoffeeBeans.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Coins.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Conditioner.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/ConstructionSite.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Countryside.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Cuckoo.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Destiny.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/DirtWalking.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Dishwasher.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Driving.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Droplets.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Fan.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/FieldWay.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Fireworks.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Forest.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Fountain.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Glass.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Heartbeat.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Horse.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/IceHockey.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Ice.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Interstellar.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Jungle.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Keyboard.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Kitchen.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Lake.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Leaves.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/LongJourney.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Magazine.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Marketplace.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Mars.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Money.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Moon.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Morning.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/MountainRoad.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Museum.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/MusicBox.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/NightPark.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/NightSea.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Ocean.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Office.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Onion.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Painting.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Pencil.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Penguin.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Piano.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/PingPong.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Port.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/PouringWater.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/PrismLight.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Rain.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Restaurant.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/River.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/RollerCoaster.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Roof.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/SandStorm.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Shovel.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Silence.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Sky.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Snow.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Storm.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Submarine.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/SummerDream.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/SummerInParis.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Supermarket.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Swamp.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Television.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Temple.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Tennis.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/ToyBlocks.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Train.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Trolley.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Typewriter.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Umbrella.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Underwater.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/VoicesOfNature.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Volcano.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Washer.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Waterfall.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Wind.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/WindAndSilence.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/WindChime.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Window.jpg"),
	[SoundPathNames[counter++]]: require("_assets/images/Yacht.jpg"),
};
